services:
  db:
    image: postgres:15
    container_name: loa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-loa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-loa}
      POSTGRES_DB: ${POSTGRES_DB:-loa}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-loa} -d ${POSTGRES_DB:-loa}']
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [app]

  server:
    build:
      context: ..
      dockerfile: Backend/Dockerfile
    container_name: loa-server
    command: npm run start:dev
    ports:
      - '4000:4000'
    env_file:
      - ../Backend/.env.development
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: ${DATABASE_URL:-postgres://loa:loa@db:5432/loa}
      ALERT_DEV_NO_COOLDOWN: '1'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../Backend:/app/Backend
      - ../tsconfig.base.json:/app/tsconfig.base.json:ro
      - /app/Backend/node_modules
    networks: [app]

  frontend:
    build:
      context: ../PwaFrontend
      dockerfile: Dockerfile
    container_name: loa-frontend
    # command: npm run dev -- --host 0.0.0.0 --port 5173
    command: sh -c "npm ci && npm run build -- --mode production && npx vite preview --host 0.0.0.0 --port 5173"
    ports:
      - '5173:5173'
    env_file:
      - ../PwaFrontend/.env.production
    environment:
      VITE_HMR_HOST: host.docker.internal # Docker 내부에서 호스트 머신을 가리키는 주소
      VITE_HMR_PORT: 5173
      CHOKIDAR_USEPOLLING: 'true'
      CHOKIDAR_INTERVAL: '200'
    volumes:
      - ../PwaFrontend:/app
      - ../tsconfig.base.json:/app/tsconfig.base.json:ro
      - /app/node_modules
    depends_on:
      - server
    networks: [app]

networks:
  app:
    driver: bridge

volumes:
  pgdata:
