// 상세 옵션 종류
export const EtcOption = {
  COMBAT: '전투 특성',
  ENGRAVE: '각인 효과',
  PENALTY: '감소 효과',
  ACCESSORY_BASE: '장신구 기본 효과',
  BRACELET_SPECIAL: '팔찌 특수 효과',
  BRACELET_COUNT: '팔찌 옵션 수량',
  REFINE: '연마 효과',
  ARK_PASSIVE: '아크패시브',
} as const;

export type EtcOptionType = (typeof EtcOption)[keyof typeof EtcOption];

export interface EtcSub {
  Value: number;
  Text: string;
  Class?: string;
  Categories?: number | number[] | null;
  Tiers?: number | number[] | null;
  EtcValues?: EtcValue[] | null;
}

export interface EtcValue {
  DisplayValue: string;
  Value: number;
  IsPercentage: boolean;
}

export interface EtcOption {
  Value: number;
  Text: string;
  Tiers: number[];
  EtcSubs: EtcSub[];
}

export const EtcOptions: EtcOption[] = [
  {
    Value: 2,
    Text: '전투 특성',
    Tiers: [2, 3, 4],
    EtcSubs: [
      { Value: 15, Text: '치명' },
      { Value: 16, Text: '특화' },
      { Value: 17, Text: '제압' },
      { Value: 18, Text: '신속' },
      { Value: 19, Text: '인내' },
      { Value: 20, Text: '숙련' },
    ],
  },
  {
    Value: 3,
    Text: '각인 효과',
    Tiers: [2, 3],
    EtcSubs: [
      { Value: 255, Text: '각성' },
      { Value: 243, Text: '강령술' },
      { Value: 242, Text: '강화 방패' },
      { Value: 288, Text: '결투의 대가' },
      { Value: 134, Text: '구슬동자' },
      { Value: 123, Text: '굳은 의지' },
      { Value: 142, Text: '급소 타격' },
      { Value: 249, Text: '기습의 대가' },
      { Value: 302, Text: '긴급구조' },
      { Value: 238, Text: '달인의 저력' },
      { Value: 254, Text: '돌격대장' },
      { Value: 168, Text: '마나 효율 증가' },
      { Value: 251, Text: '마나의 흐름' },
      { Value: 253, Text: '바리케이드' },
      { Value: 246, Text: '번개의 분노' },
      { Value: 245, Text: '부러진 뼈' },
      { Value: 236, Text: '분쇄의 주먹' },
      { Value: 235, Text: '불굴' },
      { Value: 244, Text: '선수필승' },
      { Value: 300, Text: '속전속결' },
      { Value: 121, Text: '슈퍼 차지' },
      { Value: 248, Text: '승부사' },
      { Value: 298, Text: '시선 집중' },
      { Value: 237, Text: '실드관통' },
      { Value: 299, Text: '아드레날린' },
      { Value: 111, Text: '안정된 상태' },
      { Value: 107, Text: '약자 무시' },
      { Value: 110, Text: '에테르 포식자' },
      { Value: 239, Text: '여신의 가호' },
      { Value: 141, Text: '예리한 둔기' },
      { Value: 118, Text: '원한' },
      { Value: 140, Text: '위기 모면' },
      { Value: 247, Text: '저주받은 인형' },
      { Value: 301, Text: '전문의' },
      { Value: 109, Text: '정기 흡수' },
      { Value: 303, Text: '정밀 단도' },
      { Value: 240, Text: '중갑 착용' },
      { Value: 295, Text: '질량 증가' },
      { Value: 167, Text: '최대 마나 증가' },
      { Value: 296, Text: '추진력' },
      { Value: 297, Text: '타격의 대가' },
      { Value: 202, Text: '탈출의 명수' },
      { Value: 241, Text: '폭발물 전문가' },
    ],
  },
  {
    Value: 6,
    Text: '감소 효과',
    Tiers: [2, 3],
    EtcSubs: [
      { Value: 800, Text: '공격력 감소' },
      { Value: 802, Text: '공격속도 감소' },
      { Value: 801, Text: '방어력 감소' },
      { Value: 803, Text: '이동속도 감소' },
    ],
  },
  {
    Value: 1,
    Text: '장신구 기본 효과',
    Tiers: [2, 3, 4],
    EtcSubs: [
      { Value: 3, Text: '힘' },
      { Value: 4, Text: '민첩' },
      { Value: 5, Text: '지능' },
      { Value: 6, Text: '체력' },
    ],
  },
  {
    Value: 5,
    Text: '팔찌 특수 효과',
    Tiers: [2, 3, 4],
    EtcSubs: [
      { Value: 39, Text: '강타' },
      { Value: 60, Text: '공격 및 이동 속도 증가' },
      { Value: 33, Text: '긴급 수혈' },
      { Value: 38, Text: '돌진' },
      { Value: 36, Text: '마나회수' },
      { Value: 2, Text: '마법 방어력' },
      { Value: 29, Text: '멸시' },
      { Value: 30, Text: '무시' },
      { Value: 1, Text: '물리 방어력' },
      { Value: 28, Text: '반격' },
      { Value: 31, Text: '반전' },
      { Value: 26, Text: '속공' },
      { Value: 62, Text: '시드 이하 받는 피해 감소' },
      { Value: 61, Text: '시드 이하 주는 피해 증가' },
      { Value: 35, Text: '앵콜' },
      { Value: 37, Text: '오뚝이' },
      { Value: 34, Text: '응급 처치' },
      { Value: 63, Text: '이동기 및 기상기 재사용 대기시간 감소' },
      { Value: 59, Text: '전투 자원 회복량' },
      { Value: 6, Text: '전투 중 생명력 회복량' },
      { Value: 4, Text: '최대 마나' },
      { Value: 3, Text: '최대 생명력' },
      { Value: 40, Text: '타격' },
      { Value: 27, Text: '투자' },
      { Value: 64, Text: '피격 이상 면역 효과' },
      { Value: 32, Text: '회생' },
    ],
  },
  {
    Value: 4,
    Text: '팔찌 옵션 수량',
    Tiers: [2, 3, 4],
    EtcSubs: [
      {
        Value: 1,
        Text: '고정 효과 수량',
        Class: '',
      },
      {
        Value: 2,
        Text: '부여 효과 수량',
        Class: '',
      },
    ],
  },
  {
    Value: 7,
    Text: '연마 효과',
    Tiers: [3, 4],
    EtcSubs: [
      {
        Value: 45,
        Text: '공격력 %',
        Class: '',
        Categories: [200020],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.19%', Value: 19, IsPercentage: true },
          { DisplayValue: '0.24%', Value: 24, IsPercentage: true },
          { DisplayValue: '0.29%', Value: 29, IsPercentage: true },
          { DisplayValue: '0.40%', Value: 40, IsPercentage: true },
          { DisplayValue: '0.42%', Value: 42, IsPercentage: true },
          { DisplayValue: '0.54%', Value: 54, IsPercentage: true },
          { DisplayValue: '0.66%', Value: 66, IsPercentage: true },
          { DisplayValue: '0.70%', Value: 70, IsPercentage: true },
          { DisplayValue: '0.89%', Value: 89, IsPercentage: true },
          { DisplayValue: '0.95%', Value: 95, IsPercentage: true },
          { DisplayValue: '1.09%', Value: 109, IsPercentage: true },
          { DisplayValue: '1.55%', Value: 155, IsPercentage: true },
        ],
      },
      {
        Value: 53,
        Text: '공격력 +',
        Class: '',
        Categories: null,
        Tiers: null,
        EtcValues: [
          { DisplayValue: '9', Value: 9, IsPercentage: false },
          { DisplayValue: '14', Value: 14, IsPercentage: false },
          { DisplayValue: '19', Value: 19, IsPercentage: false },
          { DisplayValue: '24', Value: 24, IsPercentage: false },
          { DisplayValue: '33', Value: 33, IsPercentage: false },
          { DisplayValue: '40', Value: 40, IsPercentage: false },
          { DisplayValue: '61', Value: 61, IsPercentage: false },
          { DisplayValue: '68', Value: 68, IsPercentage: false },
          { DisplayValue: '80', Value: 80, IsPercentage: false },
          { DisplayValue: '118', Value: 118, IsPercentage: false },
          { DisplayValue: '195', Value: 195, IsPercentage: false },
          { DisplayValue: '390', Value: 390, IsPercentage: false },
        ],
      },
      {
        Value: 44,
        Text: '낙인력',
        Class: '',
        Categories: [200010],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.96%', Value: 96, IsPercentage: true },
          { DisplayValue: '1.20%', Value: 120, IsPercentage: true },
          { DisplayValue: '1.48%', Value: 148, IsPercentage: true },
          { DisplayValue: '2.15%', Value: 215, IsPercentage: true },
          { DisplayValue: '2.16%', Value: 216, IsPercentage: true },
          { DisplayValue: '2.76%', Value: 276, IsPercentage: true },
          { DisplayValue: '3.36%', Value: 336, IsPercentage: true },
          { DisplayValue: '3.60%', Value: 360, IsPercentage: true },
          { DisplayValue: '4.60%', Value: 460, IsPercentage: true },
          { DisplayValue: '4.80%', Value: 480, IsPercentage: true },
          { DisplayValue: '5.60%', Value: 560, IsPercentage: true },
          { DisplayValue: '8.00%', Value: 800, IsPercentage: true },
        ],
      },
      {
        Value: 46,
        Text: '무기 공격력 %',
        Class: '',
        Categories: [200020],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.36%', Value: 36, IsPercentage: true },
          { DisplayValue: '0.46%', Value: 46, IsPercentage: true },
          { DisplayValue: '0.56%', Value: 56, IsPercentage: true },
          { DisplayValue: '0.80%', Value: 80, IsPercentage: true },
          { DisplayValue: '0.82%', Value: 82, IsPercentage: true },
          { DisplayValue: '1.04%', Value: 104, IsPercentage: true },
          { DisplayValue: '1.26%', Value: 126, IsPercentage: true },
          { DisplayValue: '1.36%', Value: 136, IsPercentage: true },
          { DisplayValue: '1.72%', Value: 172, IsPercentage: true },
          { DisplayValue: '1.80%', Value: 180, IsPercentage: true },
          { DisplayValue: '2.10%', Value: 210, IsPercentage: true },
          { DisplayValue: '3.00%', Value: 300, IsPercentage: true },
        ],
      },
      {
        Value: 54,
        Text: '무기 공격력 +',
        Class: '',
        Categories: null,
        Tiers: null,
        EtcValues: [
          { DisplayValue: '23', Value: 23, IsPercentage: false },
          { DisplayValue: '32', Value: 32, IsPercentage: false },
          { DisplayValue: '50', Value: 50, IsPercentage: false },
          { DisplayValue: '57', Value: 57, IsPercentage: false },
          { DisplayValue: '75', Value: 75, IsPercentage: false },
          { DisplayValue: '105', Value: 105, IsPercentage: false },
          { DisplayValue: '147', Value: 147, IsPercentage: false },
          { DisplayValue: '155', Value: 155, IsPercentage: false },
          { DisplayValue: '195', Value: 195, IsPercentage: false },
          { DisplayValue: '285', Value: 285, IsPercentage: false },
          { DisplayValue: '480', Value: 480, IsPercentage: false },
          { DisplayValue: '960', Value: 960, IsPercentage: false },
        ],
      },
      {
        Value: 57,
        Text: '상태이상 공격 지속시간',
        Class: '',
        Categories: null,
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.10%', Value: 10, IsPercentage: true },
          { DisplayValue: '0.15%', Value: 15, IsPercentage: true },
          { DisplayValue: '0.19%', Value: 19, IsPercentage: true },
          { DisplayValue: '0.20%', Value: 20, IsPercentage: true },
          { DisplayValue: '0.22%', Value: 22, IsPercentage: true },
          { DisplayValue: '0.35%', Value: 35, IsPercentage: true },
          { DisplayValue: '0.42%', Value: 42, IsPercentage: true },
          { DisplayValue: '0.45%', Value: 45, IsPercentage: true },
          { DisplayValue: '0.50%', Value: 50, IsPercentage: true },
          { DisplayValue: '0.58%', Value: 58, IsPercentage: true },
          { DisplayValue: '0.70%', Value: 70, IsPercentage: true },
          { DisplayValue: '1.00%', Value: 100, IsPercentage: true },
        ],
      },
      {
        Value: 43,
        Text: '세레나데, 신앙, 조화 게이지 획득량 증가',
        Class: '',
        Categories: [200010],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.72%', Value: 72, IsPercentage: true },
          { DisplayValue: '0.90%', Value: 90, IsPercentage: true },
          { DisplayValue: '1.11%', Value: 111, IsPercentage: true },
          { DisplayValue: '1.60%', Value: 160, IsPercentage: true },
          { DisplayValue: '1.62%', Value: 162, IsPercentage: true },
          { DisplayValue: '2.07%', Value: 207, IsPercentage: true },
          { DisplayValue: '2.52%', Value: 252, IsPercentage: true },
          { DisplayValue: '2.70%', Value: 270, IsPercentage: true },
          { DisplayValue: '3.45%', Value: 345, IsPercentage: true },
          { DisplayValue: '3.60%', Value: 360, IsPercentage: true },
          { DisplayValue: '4.20%', Value: 420, IsPercentage: true },
          { DisplayValue: '6.00%', Value: 600, IsPercentage: true },
        ],
      },
      {
        Value: 51,
        Text: '아군 공격력 강화 효과',
        Class: '',
        Categories: [200030],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.60%', Value: 60, IsPercentage: true },
          { DisplayValue: '0.76%', Value: 76, IsPercentage: true },
          { DisplayValue: '0.92%', Value: 92, IsPercentage: true },
          { DisplayValue: '1.35%', Value: 135, IsPercentage: true },
          { DisplayValue: '1.36%', Value: 136, IsPercentage: true },
          { DisplayValue: '1.72%', Value: 172, IsPercentage: true },
          { DisplayValue: '2.12%', Value: 212, IsPercentage: true },
          { DisplayValue: '2.24%', Value: 224, IsPercentage: true },
          { DisplayValue: '2.88%', Value: 288, IsPercentage: true },
          { DisplayValue: '3.00%', Value: 300, IsPercentage: true },
          { DisplayValue: '3.52%', Value: 352, IsPercentage: true },
          { DisplayValue: '5.00%', Value: 500, IsPercentage: true },
        ],
      },
      {
        Value: 52,
        Text: '아군 피해량 강화 효과',
        Class: '',
        Categories: [200030],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.90%', Value: 90, IsPercentage: true },
          { DisplayValue: '1.14%', Value: 114, IsPercentage: true },
          { DisplayValue: '1.38%', Value: 138, IsPercentage: true },
          { DisplayValue: '2.00%', Value: 200, IsPercentage: true },
          { DisplayValue: '2.04%', Value: 204, IsPercentage: true },
          { DisplayValue: '2.58%', Value: 258, IsPercentage: true },
          { DisplayValue: '3.18%', Value: 318, IsPercentage: true },
          { DisplayValue: '3.36%', Value: 336, IsPercentage: true },
          { DisplayValue: '4.32%', Value: 432, IsPercentage: true },
          { DisplayValue: '4.50%', Value: 450, IsPercentage: true },
          { DisplayValue: '5.28%', Value: 528, IsPercentage: true },
          { DisplayValue: '7.50%', Value: 750, IsPercentage: true },
        ],
      },
      {
        Value: 42,
        Text: '적에게 주는 피해 증가',
        Class: '',
        Categories: [200010],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.24%', Value: 24, IsPercentage: true },
          { DisplayValue: '0.30%', Value: 30, IsPercentage: true },
          { DisplayValue: '0.37%', Value: 37, IsPercentage: true },
          { DisplayValue: '0.54%', Value: 54, IsPercentage: true },
          { DisplayValue: '0.55%', Value: 55, IsPercentage: true },
          { DisplayValue: '0.69%', Value: 69, IsPercentage: true },
          { DisplayValue: '0.84%', Value: 84, IsPercentage: true },
          { DisplayValue: '0.90%', Value: 90, IsPercentage: true },
          { DisplayValue: '1.15%', Value: 115, IsPercentage: true },
          { DisplayValue: '1.20%', Value: 120, IsPercentage: true },
          { DisplayValue: '1.40%', Value: 140, IsPercentage: true },
          { DisplayValue: '2.00%', Value: 200, IsPercentage: true },
        ],
      },
      {
        Value: 58,
        Text: '전투 중 생명력 회복량',
        Class: '',
        Categories: null,
        Tiers: null,
        EtcValues: [
          { DisplayValue: '3', Value: 3, IsPercentage: false },
          { DisplayValue: '5', Value: 5, IsPercentage: false },
          { DisplayValue: '6', Value: 6, IsPercentage: false },
          { DisplayValue: '8', Value: 8, IsPercentage: false },
          { DisplayValue: '10', Value: 10, IsPercentage: false },
          { DisplayValue: '12', Value: 12, IsPercentage: false },
          { DisplayValue: '13', Value: 13, IsPercentage: false },
          { DisplayValue: '17', Value: 17, IsPercentage: false },
          { DisplayValue: '21', Value: 21, IsPercentage: false },
          { DisplayValue: '25', Value: 25, IsPercentage: false },
          { DisplayValue: '28', Value: 28, IsPercentage: false },
          { DisplayValue: '50', Value: 50, IsPercentage: false },
        ],
      },
      {
        Value: 56,
        Text: '최대 마나',
        Class: '',
        Categories: null,
        Tiers: null,
        EtcValues: [
          { DisplayValue: '3', Value: 3, IsPercentage: false },
          { DisplayValue: '5', Value: 5, IsPercentage: false },
          { DisplayValue: '6', Value: 6, IsPercentage: false },
          { DisplayValue: '10', Value: 10, IsPercentage: false },
          { DisplayValue: '13', Value: 13, IsPercentage: false },
          { DisplayValue: '14', Value: 14, IsPercentage: false },
          { DisplayValue: '15', Value: 15, IsPercentage: false },
          { DisplayValue: '17', Value: 17, IsPercentage: false },
          { DisplayValue: '21', Value: 21, IsPercentage: false },
          { DisplayValue: '30', Value: 30, IsPercentage: false },
        ],
      },
      {
        Value: 55,
        Text: '최대 생명력',
        Class: '',
        Categories: null,
        Tiers: null,
        EtcValues: [
          { DisplayValue: '431', Value: 431, IsPercentage: false },
          { DisplayValue: '719', Value: 719, IsPercentage: false },
          { DisplayValue: '970', Value: 970, IsPercentage: false },
          { DisplayValue: '992', Value: 992, IsPercentage: false },
          { DisplayValue: '1300', Value: 1300, IsPercentage: false },
          { DisplayValue: '1617', Value: 1617, IsPercentage: false },
          { DisplayValue: '1654', Value: 1654, IsPercentage: false },
          { DisplayValue: '2253', Value: 2253, IsPercentage: false },
          { DisplayValue: '2756', Value: 2756, IsPercentage: false },
          { DisplayValue: '3250', Value: 3250, IsPercentage: false },
          { DisplayValue: '3755', Value: 3755, IsPercentage: false },
          { DisplayValue: '6500', Value: 6500, IsPercentage: false },
        ],
      },
      {
        Value: 41,
        Text: '추가 피해',
        Class: '',
        Categories: [200010],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.31%', Value: 31, IsPercentage: true },
          { DisplayValue: '0.39%', Value: 39, IsPercentage: true },
          { DisplayValue: '0.48%', Value: 48, IsPercentage: true },
          { DisplayValue: '0.70%', Value: 70, IsPercentage: true },
          { DisplayValue: '0.90%', Value: 90, IsPercentage: true },
          { DisplayValue: '1.09%', Value: 109, IsPercentage: true },
          { DisplayValue: '1.17%', Value: 117, IsPercentage: true },
          { DisplayValue: '1.50%', Value: 150, IsPercentage: true },
          { DisplayValue: '1.60%', Value: 160, IsPercentage: true },
          { DisplayValue: '1.82%', Value: 182, IsPercentage: true },
          { DisplayValue: '2.60%', Value: 260, IsPercentage: true },
        ],
      },
      {
        Value: 49,
        Text: '치명타 적중률',
        Class: '',
        Categories: [200030],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.19%', Value: 19, IsPercentage: true },
          { DisplayValue: '0.24%', Value: 24, IsPercentage: true },
          { DisplayValue: '0.29%', Value: 29, IsPercentage: true },
          { DisplayValue: '0.40%', Value: 40, IsPercentage: true },
          { DisplayValue: '0.42%', Value: 42, IsPercentage: true },
          { DisplayValue: '0.54%', Value: 54, IsPercentage: true },
          { DisplayValue: '0.66%', Value: 66, IsPercentage: true },
          { DisplayValue: '0.70%', Value: 70, IsPercentage: true },
          { DisplayValue: '0.89%', Value: 89, IsPercentage: true },
          { DisplayValue: '0.95%', Value: 95, IsPercentage: true },
          { DisplayValue: '1.09%', Value: 109, IsPercentage: true },
          { DisplayValue: '1.55%', Value: 155, IsPercentage: true },
        ],
      },
      {
        Value: 50,
        Text: '치명타 피해',
        Class: '',
        Categories: [200030],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.48%', Value: 48, IsPercentage: true },
          { DisplayValue: '0.61%', Value: 61, IsPercentage: true },
          { DisplayValue: '0.74%', Value: 74, IsPercentage: true },
          { DisplayValue: '1.09%', Value: 109, IsPercentage: true },
          { DisplayValue: '1.10%', Value: 110, IsPercentage: true },
          { DisplayValue: '1.38%', Value: 138, IsPercentage: true },
          { DisplayValue: '1.70%', Value: 170, IsPercentage: true },
          { DisplayValue: '1.79%', Value: 179, IsPercentage: true },
          { DisplayValue: '2.30%', Value: 230, IsPercentage: true },
          { DisplayValue: '2.40%', Value: 240, IsPercentage: true },
          { DisplayValue: '2.82%', Value: 282, IsPercentage: true },
          { DisplayValue: '4.00%', Value: 400, IsPercentage: true },
        ],
      },
      {
        Value: 48,
        Text: '파티원 보호막 효과',
        Class: '',
        Categories: [200020],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.42%', Value: 42, IsPercentage: true },
          { DisplayValue: '0.54%', Value: 54, IsPercentage: true },
          { DisplayValue: '0.65%', Value: 65, IsPercentage: true },
          { DisplayValue: '0.95%', Value: 95, IsPercentage: true },
          { DisplayValue: '0.96%', Value: 96, IsPercentage: true },
          { DisplayValue: '1.21%', Value: 121, IsPercentage: true },
          { DisplayValue: '1.47%', Value: 147, IsPercentage: true },
          { DisplayValue: '1.59%', Value: 159, IsPercentage: true },
          { DisplayValue: '2.01%', Value: 201, IsPercentage: true },
          { DisplayValue: '2.10%', Value: 210, IsPercentage: true },
          { DisplayValue: '2.45%', Value: 245, IsPercentage: true },
          { DisplayValue: '3.50%', Value: 350, IsPercentage: true },
        ],
      },
      {
        Value: 47,
        Text: '파티원 회복 효과',
        Class: '',
        Categories: [200020],
        Tiers: null,
        EtcValues: [
          { DisplayValue: '0.42%', Value: 42, IsPercentage: true },
          { DisplayValue: '0.54%', Value: 54, IsPercentage: true },
          { DisplayValue: '0.65%', Value: 65, IsPercentage: true },
          { DisplayValue: '0.95%', Value: 95, IsPercentage: true },
          { DisplayValue: '0.96%', Value: 96, IsPercentage: true },
          { DisplayValue: '1.21%', Value: 121, IsPercentage: true },
          { DisplayValue: '1.47%', Value: 147, IsPercentage: true },
          { DisplayValue: '1.59%', Value: 159, IsPercentage: true },
          { DisplayValue: '2.01%', Value: 201, IsPercentage: true },
          { DisplayValue: '2.10%', Value: 210, IsPercentage: true },
          { DisplayValue: '2.45%', Value: 245, IsPercentage: true },
          { DisplayValue: '3.50%', Value: 350, IsPercentage: true },
        ],
      },
    ],
  },
  {
    Value: 8,
    Text: '아크 패시브',
    Tiers: [4],
    EtcSubs: [
      {
        Value: 1,
        Text: '깨달음',
        Class: '',
        Categories: [200010, 200020, 200030],
        Tiers: [4],
        EtcValues: null,
      },
      {
        Value: 2,
        Text: '도약',
        Class: '',
        Categories: [200040],
        Tiers: [4],
        EtcValues: null,
      },
    ],
  },
];

// 카테고리 코드 매핑 (예시)
export const CategoryEtcOptions: Record<number, EtcOptionType[]> = {
  // 장비, 보석: 상세 옵션 없음
  10000: [], // 장비
  210000: [], // 보석

  // 장신구 전체
  200000: Object.values(EtcOption),

  // 장신구 - 목걸이, 귀걸이, 반지
  200010: [
    EtcOption.COMBAT,
    EtcOption.ENGRAVE,
    EtcOption.PENALTY,
    EtcOption.ACCESSORY_BASE,
    EtcOption.REFINE,
    EtcOption.ARK_PASSIVE,
  ],
  200020: [
    EtcOption.COMBAT,
    EtcOption.ENGRAVE,
    EtcOption.PENALTY,
    EtcOption.ACCESSORY_BASE,
    EtcOption.REFINE,
    EtcOption.ARK_PASSIVE,
  ],
  200030: [
    EtcOption.COMBAT,
    EtcOption.ENGRAVE,
    EtcOption.PENALTY,
    EtcOption.ACCESSORY_BASE,
    EtcOption.REFINE,
    EtcOption.ARK_PASSIVE,
  ],

  // 장신구 - 팔찌
  200040: [
    EtcOption.COMBAT,
    EtcOption.ACCESSORY_BASE,
    EtcOption.BRACELET_SPECIAL,
    EtcOption.BRACELET_COUNT,
  ],

  // 어빌리티 스톤
  30000: [EtcOption.ENGRAVE, EtcOption.PENALTY],
};
