name: GCP OIDC Smoke Test
on: workflow_dispatch

jobs:
  auth:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: loapwa-d0c74 # 문자열 프로젝트 ID
      - run: gcloud auth list && gcloud run services list --region asia-northeast3
