# .github/workflows/deploy-cloudrun.yml
name: Build & Deploy to Cloud Run

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: loapwa-d0c74
  REGION: asia-northeast3
  AR_REPO: loa-pwa
  SERVICE: loa-api
  SQL_INSTANCE: loa-pg

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Configure Docker to Artifact Registry
        run: gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev" -q

      - name: Compute IMAGE tag
        run: |
          echo "IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/${{ env.SERVICE }}" >> $GITHUB_ENV

      # ✅ 백엔드 폴더에서 빌드/푸시
      - name: Build & Push Image
        run: |
          docker build -f Backend/Dockerfile.prod -t "$IMAGE:${{ github.sha }}" .
          docker push "$IMAGE:${{ github.sha }}"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "$SERVICE" \
            --image "$IMAGE:${{ github.sha }}" \
            --region "$REGION" \
            --allow-unauthenticated \
            --min-instances=1 \
            --max-instances=10 \
            --concurrency=80 \
            --add-cloudsql-instances "${PROJECT_ID}:${REGION}:${SQL_INSTANCE}" \
            --set-env-vars "NODE_ENV=production,FRONTEND_URL=https://loapwa-d0c74.web.app,API_URL=https://${SERVICE}-${REGION}-a.run.app,GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},GOOGLE_CALLBACK_URL=https://${SERVICE}-${REGION}-a.run.app/auth/google/callback,DB_HOST=/cloudsql/${PROJECT_ID}:${REGION}:${SQL_INSTANCE},DB_HOST=127.0.0.1,DB_PORT=5432,DB_NAME=loadb,DB_USER=yzroot,DB_PASSWORD=${{ secrets.DB_PASSWORD }},LOSTARK_API_KEY=${{ secrets.LOSTARK_API_KEY }},FCM_PROJECT_ID=${{ secrets.FCM_PROJECT_ID }},FCM_CLIENT_EMAIL=${{ secrets.FCM_CLIENT_EMAIL }},FCM_PRIVATE_KEY=${{ secrets.FCM_PRIVATE_KEY }}"
